title: Roman Baravalle, Ph.D. in Physics | Data Solver & Neuroscientist
email: baravalledatascientist@gmail.com
description: >- # This is your main meta description for Google
  Empowering TEAMS to own their data journey. Expert Data Science services in 
  Data Management, Analysis, and Automation.
url: "https://romandatascience.github.io"
baseurl: "/BaravalleDataSolver"
twitter_username: yourtwitter
github_username:  yourgithub

# SEO Settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Bar Links
header_pages:
  - mission.md
  - about.md
  - services.md
  - contact.md
